/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.tm2100.g3.proyectointegrador.View;

import ucr.ac.cr.tm2100.g3.proyectointegrador.Controller.GameController;

/**
 *
 * @author casa
 */
public class GUIOptions extends javax.swing.JFrame {

    /**
     * Creates new form GUIOptions
     */
    public GUIOptions(GameController controller) {
        initComponents();
        
        
    }

    public void escuchar(GameController controller){
        btnPlay.addActionListener(controller);
        btnHistory.addActionListener(controller);
        btnInstruction.addActionListener(controller);
        btnExit.addActionListener(controller);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlay = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnInstruction = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonJugar.png"))); // NOI18N
        btnPlay.setActionCommand("Play");
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonHistoria.png"))); // NOI18N
        btnHistory.setActionCommand("History");
        btnHistory.setBorderPainted(false);
        btnHistory.setContentAreaFilled(false);
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        btnInstruction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonInstrucciones.png"))); // NOI18N
        btnInstruction.setActionCommand("Instruction");
        btnInstruction.setBorderPainted(false);
        btnInstruction.setContentAreaFilled(false);
        getContentPane().add(btnInstruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonSalir.png"))); // NOI18N
        btnExit.setActionCommand("Exit");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Portada.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnInstruction;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
